name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT
        # Запускаем SUT,
        # имя файла SUT будет отличаться в каждой задаче.
<<<<<<< HEAD
        # & означает, что в фоновом режиме не блокируем терминал для запуска тестов,
=======
        # & означает, что в фоновом режиме не блокируем терминал для запуска тестов, 
>>>>>>> 388efdae86d4f11455a5e5c6d7bbd466ea5c6c19
        # обязательно должен быть для запуска SUT в CI
        run: java -jar ./artifacts/app-mbank.jar &
      - name: Build with Gradle
        # Запускаем автотесты
        # Для проектов на базе Selenide необходимо добавить параметр для запуска браузера
        # в headless режиме -Dselenide.headless=true, параметр --info должен остаться
<<<<<<< HEAD
        run: ./gradlew test --info
=======
        run: ./gradlew test --info  
>>>>>>> 388efdae86d4f11455a5e5c6d7bbd466ea5c6c19
